{
 "title": "Smart Helpdesk Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(flask_http_request_total, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Tickets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "helpdesk_tickets_total" }
   ]
  },
  {
   "title": "Open Tickets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "helpdesk_tickets_open" }
   ]
  },
  {
   "title": "Resolved Tickets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "helpdesk_tickets_resolved" }
   ]
  },
  {
   "title": "HTTP Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{path=~\"$endpoint\"}[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{path=~\"$endpoint\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{path=~\"$endpoint\"}[1m]))",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Tickets Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(helpdesk_ticket_created_total[$__rate_interval])",
     "legendFormat": "tickets"
    }
   ]
  }
 ]
}